# vim:syntax=python:

bluespec_library('Blinky',
    sources = [
        'Blinky.bsv',
    ],
)
bluespec_library('Dinky5Soc',
    sources = [
        'Dinky5Soc.bsv',
    ],
    deps = [
        '//hdl:Dinky5',
    ],
)
