# vim:syntax=python:

bluespec_library('Blinky',
    sources = [
        'Blinky.bsv',
    ],
)
bluespec_library('Corny5Soc',
    sources = [
        'Corny5Soc.bsv',
    ],
    deps = [
        '//hdl:Common',
        '//hdl:Rvfi',
        '//hdl:Corny5',
    ],
)
bluespec_library('Dinky5Soc',
    sources = [
        'Dinky5Soc.bsv',
    ],
    deps = [
        '//hdl:Common',
        '//hdl:Dinky5',
    ],
)
bluespec_library('Tangy5Soc',
    sources = [
        'Tangy5Soc.bsv',
    ],
    deps = [
        '//hdl:Common',
        '//hdl:Tangy5',
    ],
)
bluespec_library('Twisty5Soc',
    sources = [
        'Twisty5Soc.bsv',
    ],
    deps = [
        '//hdl:Common',
        '//hdl:Twisty5',
    ],
)
